### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by saranshsinhaa** [devs-in-tech/join-the-community#156]
**Name: Saransh Sinha** 
**Location: India** 
**Interest: Full  Stack Dev**
**Discord username(optional):-WraitH#9357**

### Why do you want to join?
> I want to join because i would like to explore the open source community

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@saranshsinhaa Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
