### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by rushikeshsuryawanshi** [devs-in-tech/join-the-community#159]
**Name: Rushikesh Suryawanshi** 
**Location: Maharashtra, India** 
**Interest: DevOps**
**Discord username(optional):- Rushikesh#0176**

### Why do you want to join?
> I want to join because I want to collaborate, meet new people, network

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@rushikeshsuryawanshi Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
