### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by sandeepvinnu** [devs-in-tech/join-the-community#160]
**Name: Sandeep Kumar** 
**Location: Hyderabad** 
**Interest: python**
**Discord username(optional):- SANDEEP KUMAR#7546**

### Why do you want to join?
> I want to join because 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by sandeepvinnu** [comment]
> Hello there!👋, Welcome to OpenSourceHub! 🚀⚡Thank you and Congratulations🎉 for opening a issue in this project. Please make sure not to start working on this issue, unless you are assigned to it.😄

i did't get any invite email

**Comment by Susmita-Dey** [comment]
@sandeepvinnu Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
