### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Adityaweb3** [devs-in-tech/join-the-community#161]
**Name: Aditya Kumar Pandey ** 
**Location: Dharwad , India ** 
**Interest: Blockchain Development , Flutter , Machine Learning **
**Discord username(optional):- ADITyA#8576**

### Why do you want to join?
> Hi, I'm Aditya a 3rd year UG Student @IIIT Dharwad . I'm in blockchain space from last 1 year . I saw this organization on github and I think with the help of this organization I will get more exposure to open source . Looking Forward to connect with great minds and upskilling my self in open source enviroment . LFG 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@Adityaweb3 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
