### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by miraz-mondal** [devs-in-tech/join-the-community#162]
**Name: Miraz Mondal** 
**Location: Kolkata** 
**Interest: Web Development and Automation**

### Why do you want to join?
> I want to join because I want to grow my knowledge in a community and networking opportunity!

**Comment by Susmita-Dey** [comment]
@miraz-mondal Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
