### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by PassionFriend** [devs-in-tech/join-the-community#163]
**Name:PassionFriend** 
**Location:** 
**Interest:**
**Discord username(optional):-**

### Why do you want to join?
Hi,
I met this community in Github.
I hope to join this community to learn more.
Thank you.

**Comment by Susmita-Dey** [comment]
@PassionFriend Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
