### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by nayanprasad** [devs-in-tech/join-the-community#164]
**Name:**  Nayan Prasad P K
**Location:** Kochi, Kerala
**Interest:** Web development, Web3
**Discord username(optional):-** Nayan Prasad#8541

### Why do you want to join?
> I want to join because I want to upskill my skills and be part of open source community by contributing to great project

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@nayanprasad Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
