### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by 0rigin-c0de** [devs-in-tech/join-the-community#168]
**Name: Sunil Kumar** 
**Location: India** 
**Interest: web development**
**Discord username(optional):- Sunil_k#2325**

> I want to join because you are so helping and i am a beginner also and you help me a lot

**Comment by Susmita-Dey** [comment]
@0rigin-c0de Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
