### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by adityassharma-ss** [devs-in-tech/join-the-community#171]
Name: Aditya Sharma
Location: India
Interest: Web-Dev | DevOps | OpenSource
Discord username(optional):- 

### Why do you want to join?
> I want to join in order to contribute to yet another opensource community

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@adityassharma-ss Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
