### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by samyabrata-maji** [devs-in-tech/join-the-community#173]
**Name:** Samyabrata Maji
**Location:** India
**Interest:** Web Development, Open Source, DevRel
**Discord username(optional):-** SamMaji#0238

### Why do you want to join?
> I want to join because I want to get involved in open source and learn from the community

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@samyabrata-maji Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
