### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by md-abid-hussain** [devs-in-tech/join-the-community#174]
**Name:** Md Abid Hussain
**Location:** Dhanbad
**Interest:** Open source, web development
**Discord username(optional):-** amomynus

### Why do you want to join?
> I want to join because I'm learning web development and being a part of community can help me to stay updated with latest tech stack in market, building connection, working on project, helping other and getting help when get stuck.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@md-abid-hussain Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
