### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by SamarthSaxena10** [devs-in-tech/join-the-community#175]
**Name:**  Samarth Saxena
**Location:** New Delhi
**Interest:** Web Development, Blockchain and Web3.0
**Discord username(optional):-** Samarth#0225

### Why do you want to join?
> I want to join because to deep dive in Open source and learn something new.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@SamarthSaxena10 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
