### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by AkashSharma001** [devs-in-tech/join-the-community#178]
**Name: Akash Sharma** 
**Location: India** 
**Interest: Full Stack, App Development, Open Source**
**Discord username(optional):- AkashSharma#1511**

### Why do you want to join?
> I want to join because I want to contribute some open source and learn from the community. I enjoy collaborating with other programmers.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@AkashSharma001 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
