### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by priyankarpal** [devs-in-tech/join-the-community#180]
**Name:** **Priyankar Pal**
**Location:** **Nadia, West Bengal, India**
**Interest:** **Open-Source, Web Development**
**Discord username(optional):-** **priyankar Pal**

### Why do you want to join?
> I want to join because I want to learn about Open-Source, New Tech, and meet to amazing people.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@priyankarpal Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
