### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Cardoso-topdev** [devs-in-tech/join-the-community#183]
Oscar Cardoso
Your heart
Web development
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I want to be a part of this awesome community.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@Cardoso-topdev Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
