### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by AnushaSP07** [devs-in-tech/join-the-community#184]
**Anusha:** 
**Bangalore:** 
**Programming and writing technical contents**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I'm a Dev and want to learn and contribute.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub).

**Comment by Susmita-Dey** [comment]
@AnushaSP07 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
