### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by kaleemqasim** [devs-in-tech/join-the-community#185]
Name: Kaleem Qasim 
Location: Pakistan
Interest: Gaming/Learning new technologies
Discord username(optional):- TempeR#1924

### Why do you want to join?
> I want to join because I want to enhance my skills as well as contributing to open source platform

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@kaleemqasim Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
