### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by ShivankUdayawal** [devs-in-tech/join-the-community#186]
**Name: Shivank Udayawal** 
**Location: Delhi-NCR** 
**Interest: Python, Data Analysis, Data Science**
**Discord username(optional):-**

### Why do you want to join?
> I want to join to enhance and learn the new skills

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@ShivankUdayawal Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
