### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Aazim-parwaz** [devs-in-tech/join-the-community#187]
Name:*Aazim Parwaz* 
Location:*Srinagar, Jammu and Kashmir* 
Interest:*Full Stack Software Development*
Discord username(optional):-*Aazim Parwaz#1425*

### Why do you want to join?
> I want to join to be a part of this community where i can learn from the peers and get opportunity to collaborate on some great projects together. 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@Aazim-parwaz Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
