### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Rishav-12** [devs-in-tech/join-the-community#188]
**Name:** Rishav Mitra
**Location:** Kolkata, West Bengal, India
**Interest:** Python, JavaScript, Open Source, Mathematics
**Discord username(optional):-** Rishav Mitra#2337

### Why do you want to join?
> I want to join because I want to get involved with awesome communities in tech.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@Rishav-12 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
