### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by niteshim0** [devs-in-tech/join-the-community#192]
**Nitesh Kushwaha** 
**Gorakhpur,Uttar Pradesh,India:** 
**Java Development,Front-End Web Development,Devops,Problem-Solving(DSA):**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I want to be a open-source contributor.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@niteshim0 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
