### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by melsorrells23** [devs-in-tech/join-the-community#195]
**Name:** Melissa Ann Sorrells
**Location:** Baton Rouge, LA, USA
**Interest:** New and first - time learning opportunities
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I want to learn and grow with a community of like - minded people.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@melsorrells23 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
