### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by HYnam** [devs-in-tech/join-the-community#196]
Name: NAM Hiu Yi 
Location: Manchester, United Kingdom 
Interest: Building mobile apps and websites. I am new in open source contribution 
Discord username(optional): Mila2000

### Why do you want to join?
>Want to learn and grow with like-minded people. 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@HYnam Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
