### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by AbhiPatel10** [devs-in-tech/join-the-community#197]
**Name:**  Abhi Patel
**Location:**  Ahmedabad, Gujarat, India
**Interest:** Web Development
**Discord username(optional):-** Abhi P. Patel#5265

### Why do you want to join?
> I want to join because it will give me the opportunity to interact with a diverse group of users and potentially gain a greater understanding of the types of information and assistance they may require

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@AbhiPatel10 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
