### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by samratghosh291** [devs-in-tech/join-the-community#198]
**Name:** SamratGhosh
**Location:** India
**Interest:** web development
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I want to explore web development

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@samratghosh291 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
