### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by akebu6** [devs-in-tech/join-the-community#199]
**Name:** Akebu
**Location:** Zambia
**Interest:** Mobile, Web Development and Data Science 
**Discord username(optional):-** akebu#5784

### Why do you want to join?
> I want to join because I want to improve on my skills as well as develop new skills while collaborating with diverse groups of people

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@akebu6 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
