### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by the-amazing-atharva** [devs-in-tech/join-the-community#201]
**Name:** Atharva Salitri
**Location:** Mumbai, India
**Interest:** Web Development, Open Source, Technical Writing
**Discord username(optional):-**

### Why do you want to join?
> I want to join because 
I want to be a part of a community where I get to learn things from the experiences of others and also provide value in terms of content of my work
You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@the-amazing-atharva Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
