### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by MohitNamdev22** [devs-in-tech/join-the-community#202]
**Name:** Mohit Namdev
**Location:** Indore, India
**Interest:** Web Development, Open Source Contribution, Graphics Designing, Video Editing
**Discord username(optional):-** Mohit Namdev#1188

### Why do you want to join?
> I was always looking for opportunities to work, learn and add value to such a large community. I liked the useful content provided by Devs in Tech. Working with Devs-In-Tech will let me grow and gain exposure. It will help me implement my existing skills at a large scale project. It will help me to connect with various similar-minded personalities.  

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
