### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by hrshtmlng** [devs-in-tech/join-the-community#203]
**Name:** Harshit Malang
**Location:** UP India
**Interest:** Web Dev|| DevRel
**Discord username(optional):-**deadsoul#7615

### Why do you want to join?
> I want to join because I'm looking for getting more into open source thatswhy

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@hrshtmlng Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
