### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by twist0R** [devs-in-tech/join-the-community#204]
**Name: Rafael Antunes** 
**Location: Portugal** 
**Interest: WebDev**
**Discord username(optional):-ANTUNES#6541**

### Why do you want to join?
>I want to join because I'm looking for getting more into open sources.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@twist0R Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
