### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by AISHIK999** [devs-in-tech/join-the-community#205]
**NAME**: Aishik Mukherjee
**LOCATION**: India
**INTERESTS**: Data Science and Machine Learning
**DISCORD USERNAME**: AISHIK999

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@AISHIK999 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
