### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by herkura** [devs-in-tech/join-the-community#206]
**Name: Hershil Piplani** 
**Location: India** 
**Interest: Front End Development, Data Analytics**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I want to connect and learn from talented people here and also share my insights as well.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@herkura Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
