### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by psmithulsourav** [devs-in-tech/join-the-community#207]
**MITHUL SOURAV** 
**Location: India** 
**Interest: Machine learning, web dev**
**Astrosmasher#0843**

### Why do you want to join?
> I want to join because i want to learn more from people and also want to contribute my knowledge

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@psmithulsourav Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
