### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by abhishekbhonde** [devs-in-tech/join-the-community#209]
**Name:Abhishek Bhonde**
**Location: Pune, Maharashtra** 
**Interest: Devops**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because it will give me the opportunity to interact with a diverse group of users and potentially gain a greater understanding of the types of information and assistance they may require.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@abhishekbhonde Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
