### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by baibhav-tiwari** [devs-in-tech/join-the-community#211]
**Name: baibhav** 
**Location: India** 
**Interest: Full Stack**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because working in a community is a best way to learn new thing as well as to meet like minded peoples.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@baibhav-tiwari Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
