### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Pal-Sandeep** [devs-in-tech/join-the-community#213]
**Sandeep Pal:** 
**Location: India** 
**Interest: DevOps**
**Discord username(optional):- **JaanlevaDushman

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@Pal-Sandeep Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
