### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by zaidahmad25** [devs-in-tech/join-the-community#216]
**Zaid Ahmad** 
**Delhi, India** 
**Web Development, Open Source, Freelancing**
**ZÆD#9055**

### Why do you want to join?
> I want to join because I am new to open source and being a part of a community will give me some exposure to open source.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@zaidahmad25 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
