### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Koras02** [devs-in-tech/join-the-community#217]
**Name:Koras02** 
**Location:*Japan* 
**Interest:*Web Development, Full Stack*
**Discord username(optional):-*konatat#5654*

### Why do you want to join?
> I want to join because To learn and share a new language

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@Koras02 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
