### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Shukla007** [devs-in-tech/join-the-community#218]
**Abhishek Shukla:** 
**India:** 
**Ai,Ml Devops,web3:**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because learn and contribute to opensource and give back to community.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@Shukla007 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
