### ISSUE TITLE
[ADD ME TO THE ORGANIZATION PLEASE]

### ISSUE THREAD

**Issue by BrycensRanch** [devs-in-tech/join-the-community#219]
**Name:** Brycen G
**Location:** Florida
**Interest:** Software Engineering, Tech Sales
**Discord username(optional):-** N/A

### Why do you want to join?
> I want to join because I love open source and I have even more contributions to OSS on my personal account. Not to mention, OSS has been a key part of my life. Without it, I believe there would be chaos when it comes to developing software and I wouldn't contribute otherwise.

Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@BrycensRanch Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.

**Comment by BrycensRanch** [comment]
Many thanks! Have a great day!
