### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Itsfoss0** [devs-in-tech/join-the-community#220]
**Name:** Ebenezer R
**Location:** Kenya
**Interest:** DevOps, Backend Engineering, Cyber Security
**Discord username(optional):-** It's Foss#8268

### Why do you want to join?
> I'd like to contribute more to open source projects

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@Itsfoss0 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
