### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by dev-rakeshshaw** [devs-in-tech/join-the-community#221]
**Name: Rakesh Shaw**  
**Location: Kolkata** 
**Interest: Python**
**Discord username(optional):- dev-rakeshshaw#3585**

### Why do you want to join?
> I want to join because I want to learn Open-Source Contribution and help others.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@dev-rakeshshaw Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
