### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by mahfuztbt** [devs-in-tech/join-the-community#222]
**Name:** Mahfuz Ronnie
**Location:**  Bangladesh
**Interest:**
**Discord username(optional):-**

### Why do you want to join?
> I want to join because want to share project and want to contribute to other project

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@mahfuztbt Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
