### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Aathirajan** [devs-in-tech/join-the-community#223]
**Name:** Aathi Rajan 
**Location:** Sivakasi,India
**Interest:** Web3, DevRel
**Discord username(optional):-** Aathiii#1185

### Why do you want to join?
> I want to connect with fellow mates and to exchange knowledge.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@Aathirajan Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
