### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by SurajPratap10** [devs-in-tech/join-the-community#224]
**Name: Suraj Pratap** 
**Location: Bihar, India** 
**Interest: Full-stack WebDev, DevRel**
**Discord username(optional):- Sam Valor #9542**

### Why do you want to join?
> I want to join because 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@SurajPratap10 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
