### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by NotPraneeth** [devs-in-tech/join-the-community#225]
**Name: Praneeth** 
**Location: Bangalore** 
**Interest: Web development**
**Discord username(optional):-**

### Why do you want to join?
> I'd love to join so that I can have an opportunity to strengthen myself in my coding skills. I do front-endweb development as of now but I also want to dive into programming languages like c, c++, Java and so on. I am also highly interested in the world of blockchain and web3 and what it has to offer along with ai/ml.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@NotPraneeth Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
