### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by thebarshablog** [devs-in-tech/join-the-community#226]
**Name: Barsha Das** 
**Location: Republic of India** 
**Interest: Product Management & Developer Advocacy in DevOps, Cloud-Native Ecosystem and Cloud Computing**
**Discord username(optional):- Barsha Das#0747**

### Why do you want to join?
> To be able to impact projects and contributors.

**Comment by Susmita-Dey** [comment]
@thebarshablog Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
