### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by jyotirmoydotdev** [devs-in-tech/join-the-community#227]
**Name:** Jyotirmoy Barman
**Location:** Tura, Meghalaya
**Interest:** Blockchain
**Discord username(optional):-**

### Why do you want to join?
Learn and Contribute

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@jyotirmoydotdev Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
