### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by kelvinparmar** [devs-in-tech/join-the-community#228]
**Name:** Kelvin Parmar
**Location:** Rajkot, Gujrat
**Interest:** DevOps , Web Development
**Discord username(optional):-** Kelvin parmar #3581

### Why do you want to join?
> I want to join because I want to give back to community which I have learnt and also learn with people and make connections with them also.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@kelvinparmar Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
