### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by pratik-wadhai** [devs-in-tech/join-the-community#230]
Pratik Wadhai
Nagpur,India
Web Dev
my github : [@pratik-wadhai](https://github.com/pratik-wadhai)

 I want to join because  i love contributing in open source

**Comment by Susmita-Dey** [comment]
@pratik-wadhai Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
