### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by himanshu1221** [devs-in-tech/join-the-community#231]
**Name: Himanshu chhatwal** 
**Location: Noida** 
**Interest: Web development, Open-source**
**Discord username(optional):- Himanshu2314#1751 **

### Why do you want to join?
> I want to join because I love meeting like-minded people, love to collaborate,and love exchanging knowledge wih others 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@himanshu1221 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
