### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by aashishpanthi** [devs-in-tech/join-the-community#233]
Name: **Aashish Panthi** 
Location: **Nepal** 
Interest: **Web development and content creation**
Discord username(optional):- **aashishpanthi#1580**

### Why do you want to join?
> I want to join because I like to explore around, make content, and help other developers in open source community.

**Comment by Susmita-Dey** [comment]
@aashishpanthi Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
