### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by LauraBigoni** [devs-in-tech/join-the-community#236]
**Name:** Laura
**Location:** Italy
**Interest:** Games, Anime, Manga, Technology
**Discord username(optional):-** Laura-#8638

### Why do you want to join?
> I want to join because it seems intresting and i found the organization from a friend on github ^^

**Comment by Susmita-Dey** [comment]
@LauraBigoni Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
