### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Sduttt** [devs-in-tech/join-the-community#237]
**Name:** Subham
**Location:** Nadia, West Bengal, India
**Interest:** Movies, Music, Books, Technology
**Discord username(optional):-** sduttt-#8769

**Why do you want to join?**
I want to be active in Open source and learn more and give more to the community.

**Comment by Susmita-Dey** [comment]
@Sduttt Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
