### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by AISHIK999** [devs-in-tech/join-the-community#238]
**Name:** Aishik Mukherjee
**Location:** Kolkata, West Bengal, India
**Interest:** Coding, cycling and traveling 
**Discord username(optional):-** 

### Why do you want to join?
> I want to join because I want to contribute more to the open source and improve my skills

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@AISHIK999 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
