### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by Yasir-Khan22** [devs-in-tech/join-the-community#239]
**Name:* Yasir Khan* 
**Location:* Lahore, Pakistan* 
**Interest:* Coding, Video Games.*
**Discord username(optional):-**

### Why do you want to join?
> I want to join because I want to produce quality developers, and help other developers in open source community.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@Yasir-Khan22 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
