### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by ni5arga** [devs-in-tech/join-the-community#241]
Name - Nisarga Adhikary 
Interests - Full Stack Development
### Why do you want to join?
> I want to join because 
I want to grow my network and learn new stuff.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@ni5arga Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
