### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by mnik7044** [devs-in-tech/join-the-community#242]
**Name: Nikhil Mishra** 
**Location: Kolkata, India** 
**Interest: Web Development, Open Source**
**Discord username(optional):- GodNik#1720**

### Why do you want to join?
> I want to join because I want to connect with like-minded people and want t build a network where we can learn and grow together in open source.

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@mnik7044 Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
