### ISSUE TITLE
[ADD ME TO THE ORGANIZATION]

### ISSUE THREAD

**Issue by rlmathguru** [devs-in-tech/join-the-community#320]
**Name:** Christopher Martindale
**Location:** New Castle, DE, United States
**Interest:** Programming
**Discord username(optional):-** chrisdevguru

### Why do you want to join?
> I want to join because 

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the DevsInTech Community [here](https://github.com/devs-in-tech).

**Comment by Susmita-Dey** [comment]
@rlmathguru Thanks for your interest. Invitations have been sent to you. Kindly accept it and make your membership public.
